### ISSUE TITLE
xray binary file not found. Router Ramips

### ISSUE THREAD

**Issue by predators46** [honwen/luci-app-xray#2]
I have made luci-app-xray xray and installed it on the router, I get an xray binary file no found error
![Screenshot_2021-03-22_063142](https://user-images.githubusercontent.com/31931530/111923347-aa062d80-8ad9-11eb-9b63-0bc0768103be.jpg)

**Comment by yuanwb1984** [comment]
在files/luci/model/cbi/xray/general.lua中18行
local has_ss = has_bin("sslocal")
