### ISSUE TITLE
inbounds端口不能正确设置

### ISSUE THREAD

**Issue by yuanwb1984** [honwen/luci-app-xray#3]
http启用8075，socks启用8070后，在/var/etc/xray.json中：
  "inbounds": [    {
      "protocol": "http",
      "port": 8075,
      "address": "0.0.0.0"
    },
    {
      "protocol": "socks",
      "port": 8075,
      "address": "0.0.0.0",
      "settings": {
        "udp": true
      }
    }
],
如果只socks启用8070，则
  "inbounds": [    {
      "protocol": "socks",
      "port": ,
      "address": "0.0.0.0",
      "settings": {
        "udp": true
      }
    }
  ],

**Comment by yuanwb1984** [comment]
files/root/etc/init.d/xray line 176

**Comment by honwen** [comment]
fixed and TKs
