### ISSUE TITLE
extra function

### ISSUE THREAD

**Issue by jack338c** [honwen/luci-app-xray#4]
My idol,your luci-app-xray is wonderful, I tried it for about 2 weeks.it's really good and fast
Now Could you add a function in xray watdog, 
For example, if grep "2" time of "Problem decteted, restarting xray" ,then Autoswitch xray server. Like put /etc/config/xray1 ,/etc/config/xray2,/etc/config/xray3  to openwrt ,switching circularly when Problem decteted
If possible , Could you give some tips or code to make it,I can't make it without your help
Thanks again

**Comment by honwen** [comment]
just wair for upstream project to add this feature

refer: https://github.com/XTLS/Xray-core/issues/914

**Comment by jack338c** [comment]
Ok,thank you
