### ISSUE TITLE
test on x86 openwrt snapshots and x86 openwrt 22.03 

### ISSUE THREAD

**Issue by jack338c** [honwen/luci-app-xray#6]
I just built your project to x86 openwrt snapshots and x86 openwrt 22.03 .both have firewall4 .
so I tried update the LUCI_DEPENDS:=+firewall4 +iptables +ipset +curl +ip +iptables-mod-tproxy
System Log shows xray No Problem and.openwrt router Self Proxy is wokring. but all lan Proxy are not working

also Got following out message
`root@OpenWrt:~# /etc/init.d/xray restart

grep: 2: No such file or directory

root@OpenWrt:~#`

Could you tell me what cause this issue

thank you

**Comment by honwen** [comment]
All my repo of luci-app-*** is  iptables-based. And firewall3 is  iptables-based, firewall4 is NOT.

Try openwrt 21.02 instead

**Comment by jack338c** [comment]
Got it ! thanks
