### ISSUE TITLE
is this fit for shadowsocks

### ISSUE THREAD

**Issue by jack338c** [honwen/luci-app-xray#8]
hello master
Same node infomation. works on luci-app-shadowsocks-rust,but not luci-app-xray (both are the newest version)
when I apply node infomation to  luci-app-xray,it will show up one "one or more required...",and it will not work
![Screenshot 2023-06-20 at 6 22 58 PM](https://github.com/honwen/luci-app-xray/assets/10782586/a7305336-74b6-44c8-b63f-e8d2a7967754)
![Screenshot 2023-06-20 at 6 22 06 PM](https://github.com/honwen/luci-app-xray/assets/10782586/093ea8db-52fb-4565-963b-371fc93fd168)

thanks

**Comment by honwen** [comment]
yes, read `/var/log/xray.log` for more info

**Comment by jack338c** [comment]
> yes, read `/var/log/xray.log` for more info

it's working now
the difference is,this time I applied ss-rust first,after reset to factory.
last time it was xray first,then ss-rust
thank you

**Comment by honwen** [comment]
`luci-app-xray` should not use with `luci-app-ss` or other luci-app like it

**Comment by jack338c** [comment]
> `luci-app-xray` should not use with `luci-app-ss` or other luci-app like it

I may didn't make it clean
I mean apply the node info of ss-rust first,not luci-app-ss-rust first
