### ISSUE TITLE
can't use transmission to download bt or megnet file

### ISSUE THREAD

**Issue by jack338c** [honwen/luci-app-xray#9]
I just found the transmission works fine if use old version [https://github.com/honwen/luci-app-xray/commit/914a6d3cb5ac61af8be2c6b5462d532458cf61df](https://github.com/honwen/luci-app-xray/commit/914a6d3cb5ac61af8be2c6b5462d532458cf61df)

but with the newest version of luci-app-xray.transmission can't download any data,neither xray or ss-rust,
I tried on or off DNS Auto-Injection and udp ,but no luck
just like p2p is blocked on openwrt
please help me
thanks

**Comment by honwen** [comment]
how about set proxy mode to global

**Comment by jack338c** [comment]
> how about set proxy mode to global
thank you for fast response
it won't help too.
I also found the n2n (a peer to peer vpn server)will not work on any pc in my op network,especially change from vless to shadowsock.

**Comment by jack338c** [comment]
update:
transmission is ok now ,sorry my fault.
but n2n (a peer to peer vpn server)will not work on any pc in my op network,especially change from vless to shadowsock.

**Comment by jack338c** [comment]
just tested this commit [https://github.com/honwen/luci-app-xray/commit/15e67fda2ba0e6ca4442588396f09ea0ec7f5a89](https://github.com/honwen/luci-app-xray/commit/15e67fda2ba0e6ca4442588396f09ea0ec7f5a89) is also ok for n2n and transmission

**Comment by honwen** [comment]
maybe Ur ss can not handle udp, related to this fix https://github.com/honwen/luci-app-xray/commit/af4a393ddf0b6ef1d2bf73e488848eacd9745059

try using with `enable_udp` disabled

**Comment by jack338c** [comment]
just solved !
thank you very much for your help
